pub mod battery;
pub mod board;
pub mod button;
pub mod buzzer;
pub mod device_id;
pub mod epd;
pub mod health;
pub mod images;
pub mod iso14443;
pub mod led;
pub mod nfct;
pub mod temperature;

// Mesh-dependent modules: LoRa radio, BLE companion, KV store, contacts, etc.
#[cfg(feature = "mesh")]
pub mod ble;
#[cfg(feature = "mesh")]
pub mod bonds;
#[cfg(feature = "mesh")]
pub mod channels;
#[cfg(feature = "mesh")]
pub mod contacts;
#[cfg(feature = "mesh")]
pub mod device_identity;
#[cfg(feature = "mesh")]
pub mod kv;
#[cfg(feature = "mesh")]
pub mod meshcore;
#[cfg(feature = "mesh")]
pub mod msg_queue;
#[cfg(feature = "mesh")]
pub mod settings;
#[cfg(feature = "mesh")]
pub mod storage;
#[cfg(feature = "mesh")]
pub mod sx1262;
